[package]
name = "dilaria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = { version = "1.1.0", optional = true }


[features]
fxhash = ["rustc-hash"]

[dev-dependencies]
insta = "1.9.0"
